name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Vercel project
        run: |
          mkdir -p .vercel
          echo '{"projectId":"prj_5vSGt6GdAsBiAWoDymGLTgw2Emug","orgId":"team_2XvRAaAKTyjtzeSMMk6pRJ3o"}' > .vercel/project.json

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}