name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_2XvRAaAKTyjtzeSMMk6pRJ3o
      VERCEL_PROJECT_ID: prj_5vSGt6GdAsBiAWoDymGLTgw2Emug
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}